[project]
authors = ["Mariano M <marianom@earthranger.com>"]
channels = ['https://repo.prefix.dev/ecoscope-workflows/', 'conda-forge']
name = "ecoscope-eda-core"
platforms = ['linux-64', 'linux-aarch64', 'osx-arm64']
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
pydantic = ">=2.0.0"
gcloud-aio-pubsub = ">=6.1.0,<7"
stamina = ">=25.1.0,<26"


# Uncomment these sections when ready to build a Conda package
# [preview]
# features = ["pixi-build"]
#
# [package]
# name = "ecoscope-eda-core"
# version = "0.1.0"
#
# [package.build]
# backend = { name = "pixi-build-python", version = "0.1.*" }
#
# [package.host-dependencies]
# python = ">=3.10"
