name: Check and maybe bump Pixi

on:
  schedule:
    - cron: "18 5 * * *"
  workflow_dispatch: {}

env:
  ECOSCOPE_ELEBOT_PAT: ${{ secrets.ECOSCOPE_ELEBOT_PAT }}

jobs:
  maybe-bump-pixi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{env.ECOSCOPE_ELEBOT_PAT}}
      - name: Check New Release
        id: check-new-release
        run: |
          CURRENT_RELEASE=$(yq -r ".env.PIXI_VERSION" .github/workflows/ci.yml)
          LATEST_RELEASE=$(
            curl -s \
            -H "Authorization: Bearer ${ECOSCOPE_ELEBOT_PAT}" \
            https://api.github.com/repos/prefix-dev/pixi/releases/latest
          )
          TAG=$(echo $LATEST_RELEASE | jq -r '.tag_name')
          IS_PRERELEASE=$(echo $LATEST_RELEASE | jq -r '.prerelease')
          RELEASE_NOTES=$(echo $LATEST_RELEASE | jq -r '.html_url')

          if ! $IS_PRERELEASE; then
            if [[ ! $TAG == $CURRENT_RELEASE ]]; then
              echo "new_version=${TAG}" >> $GITHUB_OUTPUT
              echo "release_notes=${RELEASE_NOTES}" >> $GITHUB_OUTPUT
            fi
          fi
      - name: Create pixi bump branch
        id: bump-pixi
        if: ${{steps.check-new-release.outputs.new_version}}
        env:
          NEW_VERSION: ${{steps.check-new-release.outputs.new_version}}
        run: |
          sed -i "s/PIXI_VERSION: .*/PIXI_VERSION: ${NEW_VERSION}/g" `find .github/workflows/* -not -name "bump-pixi.yml"`
          git config user.name "ecoscope-elebot"
          git config user.email "189163401+ecoscope-elebot@users.noreply.github.com"
          git checkout -b "elebot/bump-pixi-${NEW_VERSION}"
          git add -u && git commit -m "Bump pixi to ${NEW_VERSION}"
          git push origin "elebot/bump-pixi-${NEW_VERSION}"
      - name: Open PR
        id: open-pr
        if: ${{steps.check-new-release.outputs.new_version}}
        env:
          GH_TOKEN: ${{env.ECOSCOPE_ELEBOT_PAT}}
          NEW_VERSION: ${{steps.check-new-release.outputs.new_version}}
          RELEASE_NOTES: ${{steps.check-new-release.outputs.release_notes}}
        run: |
          echo "Auto-generated by: https://github.com/wildlife-dynamics/ecoscope-workflows/actions/runs/${{ inputs.invoking_workflow_run }} \
            <br>Pixi release notes: ${RELEASE_NOTES}" \
            | gh pr create \
            --body-file - \
            --title "elebot: Bump pixi version to ${NEW_VERSION}" \
            --head "elebot/bump-pixi-${NEW_VERSION}" \
            --base "main"
