name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

env:
  PIXI_VERSION: v0.48.0

jobs:
  lint:
    if: github.actor != 'ecoscope-elebot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Lint
        run: |
          pre-commit install
          pre-commit run --all-files

  mypy:
    if: github.actor != 'ecoscope-elebot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Mypy
        run: pixi run --manifest-path pixi.toml mypy-312

  test:
    if: github.actor != 'ecoscope-elebot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
      - name: Test
        run: pixi run --manifest-path pixi.toml pytest-312
